### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pe3zx** [pe3zx/mthc#15]
- [ ] Add `command: --cortex-key=` for TheHive service
- [ ] Integrate [bitnami/redis](https://hub.docker.com/r/bitnami/redis/) as additional components
- [ ] `python2-pip` is missing from Cortex serivce
- [ ] Add [recommended nginx configuration](https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#101-https-using-a-reverse-proxy) for TheHive service
- [ ] Verify misp-modules availability
